CREATE TABLE [dbo].[Teams]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [TeamName] NVARCHAR(50) NOT NULL, 
    [City] NVARCHAR(50) NOT NULL, 
    [Stadium] NVARCHAR(50) NOT NULL, 
    [Wins] NVARCHAR(1000) NOT NULL, 
    [Losses] NVARCHAR(1000) NOT NULL, 
    [Draws] NVARCHAR(1000) NOT NULL, 
    [Symbol] NVARCHAR(4) NOT NULL, 
    [Division] NVARCHAR(10) NOT NULL, 
    [Conference] NVARCHAR(4) NOT NULL
)

